require('dotenv').config();
const mongoose = require('mongoose');

const uri = process.env.MONGO_URI;

mongoose.connect(uri).then(async () => {
  console.log('Connected to MongoDB');

  // Drop existing trips
  await mongoose.connection.collection('trips').deleteMany({});
  console.log('Cleared trips collection');

  const now = new Date();
  const trips = [
    {
      title: 'Bali Soul Journey',
      slug: 'bali-soul-journey',
      tagline: 'Rituals, rice terraces and raw beauty',
      description: 'Seven days of the real Bali. Hidden temples at dawn, rice terrace walks in mist, healing ceremonies, and a surf lesson.',
      destination: 'Ubud and Canggu, Bali',
      country: 'Indonesia',
      continent: 'Asia',
      coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800'],
      pricePerPerson: 42999,
      originalPrice: 52000,
      currency: 'INR',
      days: 7,
      nights: 6,
      category: 'Cultural',
      difficulty: 'Easy',
      tags: ['beach', 'temples', 'surfing', 'wellness'],
      maxGroupSize: 14,
      minGroupSize: 2,
      departureFrom: 'Mumbai or Delhi',
      bestTimeToVisit: 'April to October',
      climate: 'Tropical 26-32C',
      language: 'Balinese, Indonesian',
      currency_local: 'IDR',
      visaRequired: false,
      highlights: ['Tegallalang rice terraces at 6am', 'Tirta Empul temple blessing', 'Cooking class', 'Beginner surf lesson', 'Tanah Lot sunset'],
      included: ['Villa accommodation', 'Daily breakfast', 'Temple fees', 'Cooking class', 'Surf lesson', 'Transfers'],
      excluded: ['International flights', 'Visa on arrival USD 35', 'Most dinners'],
      itinerary: [
        { day: 1, title: 'Arrival in Ubud', description: 'Transfer to villa. Welcome dinner.', activities: ['Airport pickup', 'Welcome dinner'], meals: { breakfast: false, lunch: false, dinner: true }, accommodation: 'Komaneka at Bisma, Ubud' },
        { day: 2, title: 'Temples and Rice Terraces', description: 'Tegallalang sunrise, Monkey Forest, Ubud Palace.', activities: ['Tegallalang', 'Monkey Forest', 'Ubud Palace'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Komaneka at Bisma, Ubud' },
        { day: 3, title: 'Cooking Class and Temple', description: 'Cooking class then Tirta Empul ceremony.', activities: ['Cooking class', 'Tirta Empul'], meals: { breakfast: true, lunch: true, dinner: false }, accommodation: 'Komaneka at Bisma, Ubud' },
        { day: 4, title: 'Mount Batur Sunrise', description: 'Optional volcano trek.', activities: ['Batur hike optional', 'Coffee plantation'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Komaneka at Bisma, Ubud' },
        { day: 5, title: 'Transfer to Canggu', description: 'Surf lesson. Tanah Lot sunset.', activities: ['Surf lesson', 'Tanah Lot'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Dojo Bali Surf Camp' },
        { day: 6, title: 'Canggu Free Day', description: 'Free day. Farewell dinner.', activities: ['Free day', 'Farewell dinner'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Dojo Bali Surf Camp' },
        { day: 7, title: 'Departure', description: 'Airport transfer.', activities: ['Airport transfer'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [
        { question: 'Do I need surf experience?', answer: 'No, the lesson is for beginners.' },
        { question: 'Is the ceremony for non-Hindus?', answer: 'Yes, all faiths are welcome.' },
      ],
      accommodationKind: 'Villa and Surf Camp',
      accommodationName: 'Komaneka at Bisma plus Dojo Bali Surf Camp',
      accommodationDetails: 'Pool villa in Ubud, surf camp in Canggu.',
      transportTo: 'Fly to Ngurah Rai International Airport',
      transportLocal: 'Private AC van throughout',
      location: { lat: -8.5069, lng: 115.2625 },
      rating: 4.8, reviewCount: 143, isFeatured: true, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
    {
      title: 'Ladakh High Altitude Circuit',
      slug: 'ladakh-high-altitude-circuit',
      tagline: 'Where silence is the loudest sound',
      description: 'Nine days through the roof of the world. Nubra Valley, Pangong Tso, and passes at 18000 feet.',
      destination: 'Leh, Ladakh',
      country: 'India',
      continent: 'Asia',
      coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
      pricePerPerson: 28999, originalPrice: 34999, currency: 'INR',
      days: 9, nights: 8, category: 'Adventure', difficulty: 'Challenging',
      tags: ['mountains', 'high altitude', 'offbeat'],
      maxGroupSize: 12, minGroupSize: 4, departureFrom: 'Delhi',
      bestTimeToVisit: 'June to September', climate: 'Cold desert 15-25C days',
      language: 'Ladakhi, Hindi', currency_local: 'INR', visaRequired: false,
      highlights: ['Khardung La at 18380 ft', 'Nubra camel safari', 'Pangong Tso sunrise', 'Hemis Monastery'],
      included: ['All accommodation', 'Breakfast and dinner', 'Permits', 'Guide', 'Oxygen cylinders'],
      excluded: ['Flights to Leh', 'Travel insurance', 'Lunch'],
      itinerary: [
        { day: 1, title: 'Arrive Leh', description: 'Rest day. Orientation walk.', activities: ['Airport pickup', 'Orientation'], meals: { breakfast: false, lunch: false, dinner: true }, accommodation: 'The Zen Guesthouse, Leh' },
        { day: 2, title: 'Leh Local', description: 'Shanti Stupa, Magnetic Hill.', activities: ['Shanti Stupa', 'Magnetic Hill'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'The Zen Guesthouse, Leh' },
        { day: 3, title: 'Nubra via Khardung La', description: 'Cross highest motorable road. Camel safari.', activities: ['Khardung La', 'Camel safari'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Nubra Organic Retreat' },
        { day: 4, title: 'Turtuk Village', description: 'Last Indian village before Pakistan.', activities: ['Turtuk walk', 'Apricot orchards'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Nubra Organic Retreat' },
        { day: 5, title: 'Nubra to Pangong', description: 'Shyok river route to Pangong.', activities: ['Shyok Valley drive', 'Pangong arrival'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Pangong Himalayan Camp' },
        { day: 6, title: 'Pangong Sunrise', description: 'Wake at 5am. The lake changes colour.', activities: ['Sunrise photography', 'South bank walk'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Pangong Himalayan Camp' },
        { day: 7, title: 'Return via Chang La', description: 'Cross Chang La at 17690 ft.', activities: ['Chang La pass', 'Thiksey Monastery'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'The Zen Guesthouse, Leh' },
        { day: 8, title: 'Hemis and Bazaar', description: 'Hemis Monastery. Leh shopping.', activities: ['Hemis Monastery', 'Leh Bazaar'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'The Zen Guesthouse, Leh' },
        { day: 9, title: 'Departure', description: 'Airport transfer.', activities: ['Airport transfer'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [{ question: 'Altitude sickness?', answer: 'We include acclimatisation day and carry oxygen.' }],
      accommodationKind: 'Guesthouse and Camp',
      accommodationName: 'Local guesthouses and Himalayan camps',
      accommodationDetails: 'Authentic local stays.',
      transportTo: 'Fly to Leh Airport', transportLocal: 'Toyota Innova SUV',
      location: { lat: 34.1526, lng: 77.5771 },
      rating: 4.9, reviewCount: 87, isFeatured: true, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
    {
      title: 'Maldives Stillwater Retreat',
      slug: 'maldives-stillwater-retreat',
      tagline: 'Glass water, endless sky, pure stillness',
      description: 'Five days in paradise. Overwater villa, turtles on the house reef, private sandbank dinner.',
      destination: 'North Male Atoll', country: 'Maldives', continent: 'Asia',
      coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800'],
      pricePerPerson: 74999, originalPrice: 90000, currency: 'INR',
      days: 5, nights: 4, category: 'Luxury', difficulty: 'Easy',
      tags: ['overwater', 'honeymoon', 'diving', 'luxury'],
      maxGroupSize: 8, minGroupSize: 2, departureFrom: 'Mumbai or Delhi',
      bestTimeToVisit: 'November to April', climate: 'Tropical 28-32C',
      language: 'Dhivehi, English', currency_local: 'MVR', visaRequired: false,
      highlights: ['Overwater villa', 'Sandbank dinner', 'Turtle snorkelling', 'Dolphin cruise'],
      included: ['Overwater villa', 'All meals', 'Seaplane', 'Snorkelling', 'Scuba intro', 'Dolphin cruise', 'Sandbank dinner'],
      excluded: ['International flights', 'Alcohol', 'Spa'],
      itinerary: [
        { day: 1, title: 'Arrival and Seaplane', description: 'Seaplane from Male to villa.', activities: ['Seaplane transfer', 'Check-in'], meals: { breakfast: false, lunch: false, dinner: true }, accommodation: 'Overwater Villa, Hurawalhi' },
        { day: 2, title: 'Reef and Scuba', description: 'Turtle snorkel. Discover Scuba.', activities: ['House reef snorkel', 'Discover Scuba'], meals: { breakfast: true, lunch: true, dinner: true }, accommodation: 'Overwater Villa' },
        { day: 3, title: 'Dolphin and Sandbank', description: 'Dolphin cruise. Private sandbank dinner.', activities: ['Dolphin cruise', 'Sandbank dinner'], meals: { breakfast: true, lunch: true, dinner: true }, accommodation: 'Overwater Villa' },
        { day: 4, title: 'Free Day', description: 'Pure relaxation.', activities: ['Paddleboarding', 'Hammock time'], meals: { breakfast: true, lunch: true, dinner: true }, accommodation: 'Overwater Villa' },
        { day: 5, title: 'Departure', description: 'Seaplane to Male.', activities: ['Seaplane to Male'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [{ question: 'Good for honeymoons?', answer: 'Designed for them.' }],
      accommodationKind: 'Overwater Villa', accommodationName: 'Hurawalhi Island Resort',
      accommodationDetails: '5 star overwater villa with glass floor.', transportTo: 'Fly to Velana Airport Male', transportLocal: 'Seaplane to resort',
      location: { lat: 5.6841, lng: 73.3822 },
      rating: 5.0, reviewCount: 62, isFeatured: true, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
    {
      title: 'Kyoto and Tokyo Cultural Immersion',
      slug: 'kyoto-tokyo-cultural-immersion',
      tagline: 'Time bends here. Let it.',
      description: 'Eight days across Japan. Tea ceremonies, bamboo groves, ramen, and bullet trains.',
      destination: 'Kyoto and Tokyo', country: 'Japan', continent: 'Asia',
      coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800'],
      pricePerPerson: 89999, originalPrice: 105000, currency: 'INR',
      days: 8, nights: 7, category: 'Cultural', difficulty: 'Easy',
      tags: ['temples', 'food', 'bullet train', 'tea ceremony'],
      maxGroupSize: 10, minGroupSize: 2, departureFrom: 'Mumbai or Delhi',
      bestTimeToVisit: 'March April or October November', climate: 'Temperate 10-22C',
      language: 'Japanese', currency_local: 'JPY',
      visaRequired: true, visaInfo: 'Tourist visa required. 5-7 days processing. We assist.',
      highlights: ['Fushimi Inari at dawn', 'Private tea ceremony', 'Arashiyama bamboo', 'Shibuya crossing', 'Shinkansen'],
      included: ['7 nights', 'Daily breakfast', 'JR Pass', 'Tea ceremony', 'Guided tours', 'Transfers'],
      excluded: ['Flights', 'Visa', 'Most meals'],
      itinerary: [
        { day: 1, title: 'Arrive Tokyo', description: 'Check in. Evening in Shinjuku.', activities: ['Check-in', 'Shinjuku walk'], meals: { breakfast: false, lunch: false, dinner: false }, accommodation: 'Keio Plaza Hotel, Shinjuku' },
        { day: 2, title: 'Tokyo Highlights', description: 'Senso-ji, Harajuku, Shibuya.', activities: ['Senso-ji', 'Harajuku', 'Shibuya crossing'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Keio Plaza Hotel' },
        { day: 3, title: 'Tsukiji and TeamLab', description: 'Breakfast sushi. TeamLab digital art.', activities: ['Tsukiji market', 'TeamLab Planets'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Keio Plaza Hotel' },
        { day: 4, title: 'Shinkansen to Kyoto', description: 'Bullet train. Ryokan check-in.', activities: ['Shinkansen', 'Ryokan check-in', 'Nishiki Market'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Tawaraya Ryokan, Kyoto' },
        { day: 5, title: 'Fushimi Inari and Tea', description: 'Dawn torii gates. Tea ceremony.', activities: ['Fushimi Inari', 'Tea ceremony', 'Gion'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Tawaraya Ryokan' },
        { day: 6, title: 'Arashiyama and Nara', description: 'Bamboo grove. Deer in Nara.', activities: ['Arashiyama', 'Nara deer park', 'Todai-ji'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Tawaraya Ryokan' },
        { day: 7, title: 'Kyoto Free and Farewell', description: 'Kinkaku-ji. Farewell dinner.', activities: ['Kinkaku-ji', 'Farewell dinner'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Tawaraya Ryokan' },
        { day: 8, title: 'Departure', description: 'Shinkansen to Tokyo. Airport.', activities: ['Shinkansen', 'Airport transfer'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [{ question: 'Is Japan expensive?', answer: 'Less than expected. Convenience stores are brilliant and cheap.' }],
      accommodationKind: 'Ryokan and Hotel', accommodationName: 'Tawaraya Ryokan Kyoto plus Keio Plaza Tokyo',
      accommodationDetails: 'Traditional inn in Kyoto, modern hotel in Tokyo.',
      transportTo: 'Fly to Narita or Haneda Airport', transportLocal: 'JR Pass plus Metro',
      location: { lat: 35.0116, lng: 135.7681 },
      rating: 4.9, reviewCount: 94, isFeatured: true, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
    {
      title: 'Santorini and Athens Escape',
      slug: 'santorini-athens-escape',
      tagline: 'Caldera sunsets that rewrite you',
      description: 'Six days in Greece. Ancient Athens and the impossible blue of Santorini.',
      destination: 'Athens and Santorini', country: 'Greece', continent: 'Europe',
      coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800'],
      pricePerPerson: 95999, originalPrice: 115000, currency: 'INR',
      days: 6, nights: 5, category: 'Luxury', difficulty: 'Easy',
      tags: ['greece', 'mediterranean', 'honeymoon', 'sailing', 'wine'],
      maxGroupSize: 10, minGroupSize: 2, departureFrom: 'Mumbai or Delhi',
      bestTimeToVisit: 'May June or September October', climate: 'Mediterranean 24-30C',
      language: 'Greek, English', currency_local: 'Euro',
      visaRequired: true, visaInfo: 'Schengen visa. 10-15 days processing. We assist.',
      highlights: ['Oia caldera sunset', 'Private catamaran', 'Acropolis at sunrise', 'Volcanic beach', 'Wine tasting'],
      included: ['5 nights including cave suite', 'Breakfast', 'Catamaran dinner', 'Acropolis tour', 'Wine tasting', 'Flights and ferry within Greece'],
      excluded: ['International flights', 'Schengen visa', 'Most meals'],
      itinerary: [
        { day: 1, title: 'Arrive Athens', description: 'Plaka evening walk.', activities: ['Check-in', 'Plaka walk'], meals: { breakfast: false, lunch: false, dinner: false }, accommodation: 'The Zillers, Athens' },
        { day: 2, title: 'Acropolis and Santorini', description: 'Acropolis at 7am. Evening flight.', activities: ['Acropolis', 'Flight to Santorini'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Mystique Cave Suite, Oia' },
        { day: 3, title: 'Oia Exploration', description: 'Village walk. Castle sunset.', activities: ['Oia walk', 'Castle sunset'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Mystique Cave Suite, Oia' },
        { day: 4, title: 'Catamaran Sail', description: 'Hot springs, red beach, dinner at sea.', activities: ['Catamaran', 'Hot springs', 'Sunset dinner'], meals: { breakfast: true, lunch: true, dinner: true }, accommodation: 'Mystique Cave Suite, Oia' },
        { day: 5, title: 'Cliff Walk and Wine', description: 'Fira to Oia walk. Santo Wines.', activities: ['Cliff walk', 'Wine tasting'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Mystique Cave Suite, Oia' },
        { day: 6, title: 'Departure', description: 'Ferry to Athens. Depart.', activities: ['Ferry', 'Departure'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [{ question: 'Best time for sunset?', answer: 'Arrive at Oia castle 90 minutes early.' }],
      accommodationKind: 'Cave Suite and Boutique Hotel', accommodationName: 'Mystique Oia plus The Zillers Athens',
      accommodationDetails: 'Cave suite with plunge pool and caldera view.',
      transportTo: 'Fly to Athens International', transportLocal: 'Ferry plus private transfers',
      location: { lat: 36.4618, lng: 25.3753 },
      rating: 4.8, reviewCount: 71, isFeatured: true, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
    {
      title: 'Rajasthan Royal Heritage Circuit',
      slug: 'rajasthan-royal-heritage-circuit',
      tagline: 'The land that time curated for you',
      description: 'Eight days across Rajasthan. Jaipur, Jodhpur, Jaisalmer desert, and Udaipur lake palaces.',
      destination: 'Jaipur Jodhpur Jaisalmer Udaipur', country: 'India', continent: 'Asia',
      coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&q=80',
      images: ['https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800'],
      pricePerPerson: 34999, originalPrice: 42000, currency: 'INR',
      days: 8, nights: 7, category: 'Cultural', difficulty: 'Easy',
      tags: ['forts', 'palaces', 'desert', 'heritage'],
      maxGroupSize: 14, minGroupSize: 4, departureFrom: 'Delhi',
      bestTimeToVisit: 'October to March', climate: 'Semi-arid 15-28C',
      language: 'Rajasthani, Hindi', currency_local: 'INR', visaRequired: false,
      highlights: ['Amber Fort at dawn', 'Desert camp under stars', 'Mehrangarh sunrise', 'Lake Pichola boat', 'Camel safari'],
      included: ['Heritage haveli stays', 'Breakfast plus 3 dinners', 'All entry fees', 'AC vehicle', 'Camel safari', 'Guide'],
      excluded: ['Flights', 'Lunch', 'Shopping'],
      itinerary: [
        { day: 1, title: 'Arrive Jaipur', description: 'Pink city evening walk.', activities: ['Check-in', 'Hawa Mahal', 'Street food'], meals: { breakfast: false, lunch: false, dinner: false }, accommodation: 'Samode Haveli, Jaipur' },
        { day: 2, title: 'Jaipur Forts', description: 'Amber Fort dawn. City Palace.', activities: ['Amber Fort', 'City Palace', 'Jantar Mantar'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Samode Haveli, Jaipur' },
        { day: 3, title: 'Jaipur to Jaisalmer', description: 'Drive to golden city.', activities: ['Travel day', 'Jaisalmer Fort'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'Suryagarh Palace, Jaisalmer' },
        { day: 4, title: 'Jaisalmer and Dunes', description: 'Fort visit. Camel safari. Stars.', activities: ['Jaisalmer Fort', 'Camel safari', 'Desert camp dinner'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Royal Desert Camp, Sam' },
        { day: 5, title: 'To Jodhpur Blue City', description: 'Drive to Jodhpur. Blue city walk.', activities: ['Travel', 'Blue city walk'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'RAAS Jodhpur' },
        { day: 6, title: 'Mehrangarh Fort', description: 'Most dramatic fort in India at sunrise.', activities: ['Mehrangarh sunrise', 'Umaid Bhawan', 'Sardar Market'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: 'RAAS Jodhpur' },
        { day: 7, title: 'To Udaipur', description: 'Lake Pichola boat at sunset. Farewell dinner.', activities: ['Drive', 'Lake Pichola boat', 'Farewell dinner'], meals: { breakfast: true, lunch: false, dinner: true }, accommodation: 'Taj Lake Palace, Udaipur' },
        { day: 8, title: 'Departure', description: 'City Palace. Airport.', activities: ['City Palace', 'Airport transfer'], meals: { breakfast: true, lunch: false, dinner: false }, accommodation: '' },
      ],
      faqs: [{ question: 'How hot?', answer: 'Oct to March is 15-28C and perfect. Avoid summer.' }],
      accommodationKind: 'Heritage Havelis', accommodationName: 'Samode, Suryagarh, RAAS, Taj Lake Palace',
      accommodationDetails: 'Every hotel is a heritage property.',
      transportTo: 'Fly Delhi to Jaipur return Udaipur to Delhi', transportLocal: 'Private AC vehicle',
      location: { lat: 26.9124, lng: 75.7873 },
      rating: 4.7, reviewCount: 112, isFeatured: false, isActive: true, soldOut: false,
      createdAt: now, updatedAt: now,
    },
  ];

  await mongoose.connection.collection('trips').insertMany(trips);
  console.log('SUCCESS: Seeded 6 trips');

  // Create admin user
  const bcrypt = require('bcryptjs');
  const usersCol = mongoose.connection.collection('users');
  const adminExists = await usersCol.findOne({ email: 'admin@voya.travel' });
  if (!adminExists) {
    const hashed = await bcrypt.hash('voya_admin_2026', 12);
    await usersCol.insertOne({
      name: 'Voya Admin',
      email: 'admin@voya.travel',
      password: hashed,
      role: 'admin',
      wishlist: [],
      createdAt: now,
      updatedAt: now,
    });
    console.log('SUCCESS: Admin created - admin@voya.travel / voya_admin_2026');
  } else {
    console.log('Admin already exists');
  }

  process.exit(0);
}).catch(e => {
  console.error('ERROR:', e.message);
  process.exit(1);
});
