// Additional curated journeys. Referenced destinations/pricing inspired by popular
// Indian-market tour operators. Each is a full Trip document (minus timestamps/_id).

const M = (b, l, d) => ({ breakfast: b, lunch: l, dinner: d });

module.exports = [
  {
    title: 'Vietnam Highlights Expedition', slug: 'vietnam-highlights-expedition',
    tagline: 'Lanterns, limestone bays and street-food dawns',
    description: 'Eight days across Vietnam — the frenetic charm of Hanoi, an overnight cruise through the limestone karsts of Ha Long Bay, and the lantern-lit old town of Hoi An. Pho at sunrise, tailoring in the afternoon, egg coffee at dusk.',
    destination: 'Hanoi, Ha Long and Hoi An', country: 'Vietnam', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800', 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800'],
    pricePerPerson: 49999, originalPrice: 62000, currency: 'INR',
    days: 8, nights: 7, category: 'Cultural', difficulty: 'Easy',
    tags: ['street food', 'cruise', 'culture', 'beach', 'photography'],
    maxGroupSize: 14, minGroupSize: 2, departureFrom: 'Delhi or Mumbai',
    bestTimeToVisit: 'February to April or September to November', climate: 'Tropical 22-32C',
    language: 'Vietnamese', currency_local: 'VND', visaRequired: true,
    visaInfo: 'E-visa required for Indian passport holders. 3-5 working days. We assist with the application.',
    highlights: ['Overnight junk cruise in Ha Long Bay', 'Hanoi Old Quarter food walk', 'Hoi An lantern old town', 'Custom tailoring in Hoi An', 'Egg coffee at a hidden cafe'],
    included: ['7 nights accommodation', 'Ha Long overnight cruise', 'Daily breakfast plus cruise meals', 'Domestic flight Hanoi to Da Nang', 'Guided city tours', 'Airport transfers'],
    excluded: ['International flights', 'Vietnam e-visa', 'Most lunches and dinners', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Hanoi', description: 'Transfer to the Old Quarter. Evening street-food walk through the buzzing lanes.', activities: ['Airport pickup', 'Old Quarter food walk'], meals: M(false, false, true), accommodation: 'La Siesta Premium, Hanoi' },
      { day: 2, title: 'Hanoi City', description: 'Ho Chi Minh complex, Temple of Literature, Train Street, and a water-puppet show.', activities: ['Temple of Literature', 'Train Street', 'Water puppet show'], meals: M(true, false, false), accommodation: 'La Siesta Premium, Hanoi' },
      { day: 3, title: 'Ha Long Bay Cruise', description: 'Drive to Ha Long. Board an overnight junk. Kayak among the karsts, sunset on deck.', activities: ['Junk cruise', 'Kayaking', 'Sunset on deck'], meals: M(true, true, true), accommodation: 'Overnight Cruise, Ha Long Bay' },
      { day: 4, title: 'Cruise to Hanoi, Fly to Da Nang', description: 'Tai chi at dawn, cave visit, then transfer back and evening flight south to Da Nang.', activities: ['Sunrise tai chi', 'Sung Sot Cave', 'Flight to Da Nang'], meals: M(true, false, false), accommodation: 'Little Riverside, Hoi An' },
      { day: 5, title: 'Hoi An Old Town', description: 'Wander the lantern-lit UNESCO old town. Order custom tailoring. Basket-boat ride.', activities: ['Old town walk', 'Tailoring', 'Basket boat ride'], meals: M(true, false, false), accommodation: 'Little Riverside, Hoi An' },
      { day: 6, title: 'Cooking Class and Beach', description: 'Morning market and Vietnamese cooking class. Afternoon free on An Bang beach.', activities: ['Cooking class', 'An Bang beach'], meals: M(true, true, false), accommodation: 'Little Riverside, Hoi An' },
      { day: 7, title: 'Free Day and Farewell', description: 'Collect your tailored clothes. Optional My Son ruins. Farewell riverside dinner.', activities: ['Free morning', 'My Son optional', 'Farewell dinner'], meals: M(true, false, true), accommodation: 'Little Riverside, Hoi An' },
      { day: 8, title: 'Departure', description: 'Transfer to Da Nang airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is the Ha Long cruise private?', answer: 'It is a shared boutique cruise with a private cabin for your group.' },
      { question: 'How long does tailoring take in Hoi An?', answer: '24-48 hours. Order on day 5 and collect on day 7.' },
    ],
    accommodationKind: 'Boutique Hotels and Cruise', accommodationName: 'La Siesta Hanoi, overnight junk, Little Riverside Hoi An',
    accommodationDetails: 'Central boutique stays plus one night on a traditional cruise.',
    transportTo: 'Fly to Noi Bai International Airport, Hanoi', transportLocal: 'Private AC vehicle plus one domestic flight',
    location: { lat: 21.0285, lng: 105.8542 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Thailand Islands and Bangkok', slug: 'thailand-islands-and-bangkok',
    tagline: 'Temples, tuk-tuks and turquoise water',
    description: 'Seven days from the neon buzz of Bangkok to the limestone cliffs of Krabi and the beaches of Phuket. Rooftop bars, floating markets, island-hopping by longtail, and the best pad thai of your life.',
    destination: 'Bangkok, Phuket and Krabi', country: 'Thailand', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800', 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800'],
    pricePerPerson: 44999, originalPrice: 55000, currency: 'INR',
    days: 7, nights: 6, category: 'Beach', difficulty: 'Easy',
    tags: ['beach', 'islands', 'nightlife', 'temples', 'snorkelling'],
    maxGroupSize: 16, minGroupSize: 2, departureFrom: 'Delhi, Mumbai or Kolkata',
    bestTimeToVisit: 'November to March', climate: 'Tropical 28-34C',
    language: 'Thai', currency_local: 'THB', visaRequired: false,
    highlights: ['Phi Phi Islands longtail tour', 'Grand Palace and Wat Arun', 'Rooftop bar over Bangkok', 'James Bond Island', 'Floating market breakfast'],
    included: ['6 nights accommodation', 'Daily breakfast', 'Phi Phi island tour', 'Domestic flight Bangkok to Phuket', 'Airport transfers', 'City tour'],
    excluded: ['International flights', 'Most meals', 'Optional activities', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Bangkok', description: 'Transfer to hotel. Evening at a Sukhumvit rooftop bar.', activities: ['Airport pickup', 'Rooftop bar'], meals: M(false, false, false), accommodation: 'Novotel Sukhumvit, Bangkok' },
      { day: 2, title: 'Bangkok Temples', description: 'Grand Palace, Wat Pho reclining Buddha, Wat Arun, and a longtail canal ride.', activities: ['Grand Palace', 'Wat Pho', 'Canal ride'], meals: M(true, false, false), accommodation: 'Novotel Sukhumvit, Bangkok' },
      { day: 3, title: 'Fly to Phuket', description: 'Floating market visit, then fly south. Sunset at Patong beach.', activities: ['Floating market', 'Flight to Phuket', 'Patong sunset'], meals: M(true, false, false), accommodation: 'Katathani, Phuket' },
      { day: 4, title: 'Phi Phi Islands', description: 'Full-day longtail tour — Maya Bay, snorkelling, Monkey Beach, and lunch on the water.', activities: ['Phi Phi tour', 'Snorkelling', 'Maya Bay'], meals: M(true, true, false), accommodation: 'Katathani, Phuket' },
      { day: 5, title: 'Phang Nga Bay', description: 'James Bond Island, sea-cave canoeing, and a beach BBQ.', activities: ['James Bond Island', 'Sea cave canoe'], meals: M(true, true, false), accommodation: 'Katathani, Phuket' },
      { day: 6, title: 'Free Beach Day', description: 'Nothing scheduled. Spa, dive, or simply do nothing by the sea.', activities: ['Free day', 'Optional diving'], meals: M(true, false, false), accommodation: 'Katathani, Phuket' },
      { day: 7, title: 'Departure', description: 'Transfer to Phuket airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is Thailand good for first-timers?', answer: 'Absolutely — it is one of the easiest, friendliest destinations in Asia.' },
      { question: 'Can non-swimmers do the island tour?', answer: 'Yes, life jackets are provided and snorkelling is optional.' },
    ],
    accommodationKind: 'Beach Resorts and City Hotel', accommodationName: 'Novotel Bangkok plus Katathani Phuket',
    accommodationDetails: 'Modern city hotel and a beachfront resort in the south.',
    transportTo: 'Fly to Suvarnabhumi Airport, Bangkok', transportLocal: 'Domestic flight plus private transfers',
    location: { lat: 7.8804, lng: 98.3923 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Sri Lanka Hills and Coast', slug: 'sri-lanka-hills-and-coast',
    tagline: 'Tea trains, temples and turtle beaches',
    description: 'Eight days across the teardrop isle — the tooth relic of Kandy, the world-famous blue train to Ella, misty tea estates, and the Dutch-fort charm of Galle. One of the most scenic train rides on earth included.',
    destination: 'Kandy, Ella and Galle', country: 'Sri Lanka', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1546708973-b339540b5162?w=800'],
    pricePerPerson: 52999, originalPrice: 64000, currency: 'INR',
    days: 8, nights: 7, category: 'Cultural', difficulty: 'Easy',
    tags: ['tea', 'train', 'temples', 'beach', 'wildlife'],
    maxGroupSize: 14, minGroupSize: 2, departureFrom: 'Chennai, Delhi or Mumbai',
    bestTimeToVisit: 'December to March', climate: 'Tropical 24-32C',
    language: 'Sinhala, Tamil', currency_local: 'LKR', visaRequired: true,
    visaInfo: 'ETA required for Indian passport holders. Quick online approval. We assist.',
    highlights: ['Kandy to Ella blue train', 'Temple of the Sacred Tooth Relic', 'Nine Arches Bridge', 'Galle Fort at sunset', 'Yala safari for leopards'],
    included: ['7 nights accommodation', 'Daily breakfast', 'Scenic train tickets', 'Yala safari jeep', 'All entry fees', 'Private vehicle and guide'],
    excluded: ['International flights', 'Sri Lanka ETA', 'Most meals', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Colombo, drive to Kandy', description: 'Airport pickup and scenic drive to the hill capital. Evening lake walk.', activities: ['Airport pickup', 'Kandy Lake'], meals: M(false, false, true), accommodation: 'Earls Regency, Kandy' },
      { day: 2, title: 'Kandy Culture', description: 'Temple of the Tooth, botanical gardens, and a Kandyan dance performance.', activities: ['Temple of the Tooth', 'Peradeniya Gardens', 'Kandyan dance'], meals: M(true, false, false), accommodation: 'Earls Regency, Kandy' },
      { day: 3, title: 'Blue Train to Ella', description: 'Board the famous hill-country train. Tea estates, tunnels and viaducts to Ella.', activities: ['Scenic train ride', 'Tea estate visit'], meals: M(true, false, false), accommodation: '98 Acres Resort, Ella' },
      { day: 4, title: 'Ella Highlights', description: 'Nine Arches Bridge, Little Adams Peak hike, and a tea-factory tour.', activities: ['Nine Arches Bridge', 'Little Adams Peak', 'Tea factory'], meals: M(true, false, false), accommodation: '98 Acres Resort, Ella' },
      { day: 5, title: 'Yala Safari', description: 'Drive to Yala. Afternoon jeep safari in search of leopards and elephants.', activities: ['Yala jeep safari'], meals: M(true, false, true), accommodation: 'Cinnamon Wild, Yala' },
      { day: 6, title: 'Coast to Galle', description: 'Drive along the south coast to Galle. Explore the Dutch Fort ramparts at sunset.', activities: ['Coastal drive', 'Galle Fort walk'], meals: M(true, false, false), accommodation: 'Le Grand, Galle' },
      { day: 7, title: 'Galle and Beach', description: 'Free morning on Unawatuna beach. Optional whale watching or stilt-fishing photo stop.', activities: ['Unawatuna beach', 'Optional whale watching'], meals: M(true, false, false), accommodation: 'Le Grand, Galle' },
      { day: 8, title: 'Departure', description: 'Transfer to Colombo airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is the train ride bookable in advance?', answer: 'Yes, we reserve reserved-class seats so you are guaranteed a window.' },
      { question: 'Are leopard sightings guaranteed at Yala?', answer: 'Yala has the highest leopard density in the world, but wildlife is never guaranteed.' },
    ],
    accommodationKind: 'Hill Resorts and Fort Hotel', accommodationName: 'Earls Kandy, 98 Acres Ella, Cinnamon Wild, Le Grand Galle',
    accommodationDetails: 'Tea-country resorts, a safari lodge, and a boutique fort stay.',
    transportTo: 'Fly to Bandaranaike International Airport, Colombo', transportLocal: 'Private vehicle plus scenic train',
    location: { lat: 7.2906, lng: 80.6337 },
    isFeatured: false, rating: 0, reviewCount: 0,
  },
  {
    title: 'Spiti Valley Backpacking Circuit', slug: 'spiti-valley-backpacking-circuit',
    tagline: 'The middle land between India and Tibet',
    description: 'Eight days through the cold desert of Spiti — thousand-year-old monasteries, the highest villages in the world, fossil hunting at Langza, and star-blanketed nights at Kaza. Raw, remote, and utterly humbling.',
    destination: 'Kaza, Spiti Valley', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
    pricePerPerson: 24999, originalPrice: 31000, currency: 'INR',
    days: 8, nights: 7, category: 'Adventure', difficulty: 'Challenging',
    tags: ['mountains', 'monasteries', 'high altitude', 'backpacking', 'offbeat'],
    maxGroupSize: 12, minGroupSize: 4, departureFrom: 'Delhi or Manali',
    bestTimeToVisit: 'June to September', climate: 'Cold desert 15-25C days, near 0C nights',
    language: 'Spiti Bhoti, Hindi', currency_local: 'INR', visaRequired: false,
    highlights: ['Key Monastery perched on a cliff', 'Hikkim, the highest post office', 'Langza fossil village', 'Chandratal moon lake', 'Pin Valley National Park'],
    included: ['All accommodation homestays and guesthouses', 'Breakfast and dinner daily', 'Tempo Traveller transport', 'Inner Line Permits', 'Local guide'],
    excluded: ['Travel to Manali or Shimla', 'Lunch', 'Travel insurance', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Shimla to Chitkul', description: 'Drive through Kinnaur to Chitkul, the last village on the Indo-Tibet road.', activities: ['Scenic drive', 'Chitkul village walk'], meals: M(false, false, true), accommodation: 'Homestay, Sangla' },
      { day: 2, title: 'Sangla to Nako', description: 'Cross into the arid landscape. Visit the ancient Nako lake and monastery.', activities: ['Nako Lake', 'Nako Monastery'], meals: M(true, false, true), accommodation: 'Guesthouse, Nako' },
      { day: 3, title: 'Nako to Tabo', description: 'Visit Tabo Monastery, the "Ajanta of the Himalayas", over 1000 years old.', activities: ['Tabo Monastery', 'Dhankar detour'], meals: M(true, false, true), accommodation: 'Guesthouse, Tabo' },
      { day: 4, title: 'Dhankar and Pin Valley', description: 'Dhankar fort-monastery and lake hike, then into the green Pin Valley.', activities: ['Dhankar Lake hike', 'Pin Valley'], meals: M(true, false, true), accommodation: 'Homestay, Mudh' },
      { day: 5, title: 'Kaza and the Highest Villages', description: 'Key Monastery, Kibber, Hikkim post office, Komic, and fossil-rich Langza.', activities: ['Key Monastery', 'Hikkim post office', 'Langza fossils'], meals: M(true, false, true), accommodation: 'Homestay, Kaza' },
      { day: 6, title: 'Kaza to Chandratal', description: 'Cross Kunzum Pass to the crescent-shaped moon lake. Camp under the stars.', activities: ['Kunzum Pass', 'Chandratal Lake'], meals: M(true, false, true), accommodation: 'Camp, Chandratal' },
      { day: 7, title: 'Chandratal to Manali', description: 'Cross Rohtang Pass and descend into green Manali.', activities: ['Rohtang Pass', 'Arrive Manali'], meals: M(true, false, false), accommodation: 'Hotel, Manali' },
      { day: 8, title: 'Departure', description: 'Depart Manali.', activities: ['Departure'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Do I need to be very fit?', answer: 'A basic fitness level helps. We acclimatise gradually to manage the altitude.' },
      { question: 'Is there mobile network?', answer: 'Only BSNL and Jio postpaid work sporadically. Embrace the digital detox.' },
    ],
    accommodationKind: 'Homestays and Camps', accommodationName: 'Local homestays, guesthouses and one alpine camp',
    accommodationDetails: 'Authentic Spitian homestays. Simple, warm, and unforgettable.',
    transportTo: 'Reach Shimla by road or train; trip ends in Manali', transportLocal: 'Tempo Traveller throughout',
    location: { lat: 32.2270, lng: 78.0716 },
    isFeatured: false, rating: 0, reviewCount: 0,
  },
  {
    title: 'Kerala Backwaters and Hills', slug: 'kerala-backwaters-and-hills',
    tagline: 'Gods own country, at its own pace',
    description: "Six days through Kerala's greens — tea-carpeted Munnar, an overnight houseboat on the Alleppey backwaters, an Ayurvedic massage, and the colonial lanes of Fort Kochi. Slow travel, done right.",
    destination: 'Munnar, Alleppey and Kochi', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800', 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800'],
    pricePerPerson: 32999, originalPrice: 39000, currency: 'INR',
    days: 6, nights: 5, category: 'Honeymoon', difficulty: 'Easy',
    tags: ['backwaters', 'tea', 'houseboat', 'ayurveda', 'honeymoon'],
    maxGroupSize: 12, minGroupSize: 2, departureFrom: 'Any metro',
    bestTimeToVisit: 'September to March', climate: 'Tropical 23-32C',
    language: 'Malayalam', currency_local: 'INR', visaRequired: false,
    highlights: ['Overnight Alleppey houseboat', 'Munnar tea plantations', 'Ayurvedic massage', 'Fort Kochi and Chinese nets', 'Kathakali performance'],
    included: ['5 nights including houseboat', 'Daily breakfast plus houseboat meals', 'Munnar tea museum', 'Ayurvedic massage session', 'Private AC vehicle', 'Airport transfers'],
    excluded: ['Flights', 'Most lunches and dinners', 'Optional activities', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Kochi to Munnar', description: 'Drive up into the hills through waterfalls and spice plantations.', activities: ['Scenic drive', 'Spice plantation'], meals: M(false, false, false), accommodation: 'Fragrant Nature, Munnar' },
      { day: 2, title: 'Munnar Tea Country', description: 'Tea museum, Eravikulam National Park, Mattupetty dam, and Echo Point.', activities: ['Tea museum', 'Eravikulam park', 'Echo Point'], meals: M(true, false, false), accommodation: 'Fragrant Nature, Munnar' },
      { day: 3, title: 'Munnar to Alleppey Houseboat', description: 'Descend to the backwaters and board a private houseboat. Cruise the palm-lined canals.', activities: ['Houseboat check-in', 'Backwater cruise'], meals: M(true, true, true), accommodation: 'Private Houseboat, Alleppey' },
      { day: 4, title: 'Alleppey to Kochi', description: 'Sunrise on the water, then transfer to Fort Kochi. Evening Kathakali show.', activities: ['Sunrise cruise', 'Kathakali performance'], meals: M(true, false, false), accommodation: 'Forte Kochi, Fort Kochi' },
      { day: 5, title: 'Fort Kochi', description: 'Chinese fishing nets, St Francis Church, spice market, and an Ayurvedic massage.', activities: ['Chinese nets', 'Spice market', 'Ayurvedic massage'], meals: M(true, false, false), accommodation: 'Forte Kochi, Fort Kochi' },
      { day: 6, title: 'Departure', description: 'Transfer to Kochi airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is the houseboat private?', answer: 'Yes, you get a private houseboat with a dedicated cook and crew.' },
      { question: 'Good for honeymoons?', answer: 'One of our most popular honeymoon itineraries.' },
    ],
    accommodationKind: 'Resorts and Houseboat', accommodationName: 'Fragrant Nature Munnar, private houseboat, Forte Kochi',
    accommodationDetails: 'Hill resort, a private houseboat night, and a heritage Fort Kochi stay.',
    transportTo: 'Fly to Cochin International Airport', transportLocal: 'Private AC vehicle plus houseboat',
    location: { lat: 9.4981, lng: 76.3388 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Kashmir Paradise Retreat', slug: 'kashmir-paradise-retreat',
    tagline: 'If there is a heaven on earth, it is here',
    description: 'Six days in the Valley — a shikara glide across Dal Lake, a night in a carved wooden houseboat, the meadows of Gulmarg by gondola, and the pine valleys of Pahalgam. Saffron, samovars, and snow-capped peaks.',
    destination: 'Srinagar, Gulmarg and Pahalgam', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800'],
    pricePerPerson: 29999, originalPrice: 37000, currency: 'INR',
    days: 6, nights: 5, category: 'Family', difficulty: 'Easy',
    tags: ['lakes', 'meadows', 'houseboat', 'gondola', 'family'],
    maxGroupSize: 16, minGroupSize: 2, departureFrom: 'Delhi or any metro',
    bestTimeToVisit: 'March to October', climate: 'Temperate 10-25C summer',
    language: 'Kashmiri, Urdu', currency_local: 'INR', visaRequired: false,
    highlights: ['Shikara ride on Dal Lake', 'Night in a Dal Lake houseboat', 'Gulmarg Gondola', 'Betaab Valley in Pahalgam', 'Mughal Gardens'],
    included: ['5 nights including a houseboat night', 'Daily breakfast and dinner', 'Shikara ride', 'All transfers and sightseeing', 'Gondola phase 1 tickets'],
    excluded: ['Flights', 'Lunch', 'Pony rides and optional activities', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Srinagar', description: 'Transfer to a Dal Lake houseboat. Evening shikara ride to the floating market.', activities: ['Airport pickup', 'Shikara ride'], meals: M(false, false, true), accommodation: 'Deluxe Houseboat, Dal Lake' },
      { day: 2, title: 'Srinagar and Mughal Gardens', description: 'Nishat and Shalimar gardens, Shankaracharya temple, and the old city.', activities: ['Mughal Gardens', 'Shankaracharya', 'Old city'], meals: M(true, false, true), accommodation: 'Hotel, Srinagar' },
      { day: 3, title: 'Gulmarg Day Trip', description: 'Drive to the meadow of flowers. Ride the Gulmarg Gondola for Himalayan views.', activities: ['Gulmarg Gondola', 'Meadow walk'], meals: M(true, false, true), accommodation: 'Hotel, Srinagar' },
      { day: 4, title: 'Pahalgam', description: 'Drive through saffron fields to Pahalgam. Betaab Valley and Aru Valley.', activities: ['Betaab Valley', 'Aru Valley'], meals: M(true, false, true), accommodation: 'Hotel, Pahalgam' },
      { day: 5, title: 'Pahalgam to Srinagar', description: 'Lidder river walk, then return to Srinagar for last-minute handicraft shopping.', activities: ['Lidder river', 'Handicraft shopping'], meals: M(true, false, true), accommodation: 'Hotel, Srinagar' },
      { day: 6, title: 'Departure', description: 'Transfer to Srinagar airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is Kashmir safe for families?', answer: 'The tourist circuit is well-managed and popular with families year-round.' },
      { question: 'Will there be snow?', answer: 'Gulmarg has snow into spring; winter months see snow across the valley.' },
    ],
    accommodationKind: 'Houseboat and Hotels', accommodationName: 'Dal Lake houseboat plus valley hotels',
    accommodationDetails: 'A traditional carved houseboat night plus comfortable valley hotels.',
    transportTo: 'Fly to Srinagar International Airport', transportLocal: 'Private vehicle throughout',
    location: { lat: 34.0837, lng: 74.7973 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Enchanting Georgia', slug: 'enchanting-georgia',
    tagline: 'Where Europe and Asia share a table',
    description: 'Seven days in the Caucasus — cobbled Tbilisi, cliff-clinging Kazbegi churches, cave cities, and the wine cradle of Kakheti. Supra feasts, sulphur baths, and mountains that fall straight out of a fairytale.',
    destination: 'Tbilisi, Kazbegi and Kakheti', country: 'Georgia', continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1605540436563-5bca919ae766?w=800', 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800'],
    pricePerPerson: 64999, originalPrice: 78000, currency: 'INR',
    days: 7, nights: 6, category: 'Cultural', difficulty: 'Easy',
    tags: ['wine', 'mountains', 'culture', 'food', 'offbeat'],
    maxGroupSize: 14, minGroupSize: 2, departureFrom: 'Delhi or Mumbai',
    bestTimeToVisit: 'May to October', climate: 'Temperate 15-28C summer',
    language: 'Georgian', currency_local: 'GEL', visaRequired: true,
    visaInfo: 'E-visa required for Indian passport holders. Straightforward online process. We assist.',
    highlights: ['Gergeti Trinity Church at Kazbegi', 'Old Tbilisi and sulphur baths', 'Uplistsikhe cave city', 'Kakheti wine tasting', 'Traditional supra feast'],
    included: ['6 nights accommodation', 'Daily breakfast plus 2 dinners', 'Wine tastings', 'All sightseeing and entries', 'Private vehicle and guide', 'Airport transfers'],
    excluded: ['International flights', 'Georgia e-visa', 'Most meals', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Tbilisi', description: 'Transfer to the old town. Evening walk and dinner with live polyphonic singing.', activities: ['Airport pickup', 'Old town walk'], meals: M(false, false, true), accommodation: 'Hotel, Old Tbilisi' },
      { day: 2, title: 'Tbilisi City', description: 'Narikala fortress, sulphur baths district, Holy Trinity Cathedral, and the cable car.', activities: ['Narikala fortress', 'Sulphur baths', 'Cable car'], meals: M(true, false, false), accommodation: 'Hotel, Old Tbilisi' },
      { day: 3, title: 'Kazbegi Day Trip', description: 'Drive the Military Highway to Gergeti Trinity Church beneath Mount Kazbek.', activities: ['Ananuri fortress', 'Gergeti Trinity Church'], meals: M(true, false, false), accommodation: 'Hotel, Old Tbilisi' },
      { day: 4, title: 'Mtskheta and Uplistsikhe', description: 'Ancient capital Mtskheta and the rock-hewn cave city of Uplistsikhe.', activities: ['Mtskheta', 'Uplistsikhe cave city'], meals: M(true, false, false), accommodation: 'Hotel, Old Tbilisi' },
      { day: 5, title: 'Kakheti Wine Region', description: 'Sighnaghi the town of love, and family-run wineries for tastings and a supra.', activities: ['Sighnaghi', 'Winery tastings', 'Supra feast'], meals: M(true, false, true), accommodation: 'Guesthouse, Sighnaghi' },
      { day: 6, title: 'Return to Tbilisi', description: 'Bodbe Monastery, then back to Tbilisi. Free afternoon for shopping and cafes.', activities: ['Bodbe Monastery', 'Free afternoon'], meals: M(true, false, false), accommodation: 'Hotel, Old Tbilisi' },
      { day: 7, title: 'Departure', description: 'Transfer to Tbilisi airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Is Georgia vegetarian-friendly?', answer: 'Very — khachapuri, lobio, badrijani and more make it a vegetarian delight.' },
      { question: 'Is it good value?', answer: 'Georgia offers European scenery at a fraction of Western European prices.' },
    ],
    accommodationKind: 'Boutique Hotels and Guesthouse', accommodationName: 'Old Tbilisi boutique hotel plus a Kakheti guesthouse',
    accommodationDetails: 'Characterful old-town stays and one wine-country guesthouse.',
    transportTo: 'Fly to Tbilisi International Airport', transportLocal: 'Private vehicle throughout',
    location: { lat: 41.7151, lng: 44.8271 },
    isFeatured: false, rating: 0, reviewCount: 0,
  },
  {
    title: 'Ultimate Iceland Expedition', slug: 'ultimate-iceland-expedition',
    tagline: 'Fire, ice, and the dancing lights',
    description: 'Nine days circling the land of ice and fire — thundering waterfalls, black-sand beaches, glacier lagoons, geothermal spas, and, in season, the aurora overhead. A road trip like no other.',
    destination: 'Reykjavik and the Ring Road', country: 'Iceland', continent: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800'],
    pricePerPerson: 249999, originalPrice: 290000, currency: 'INR',
    days: 9, nights: 8, category: 'Luxury', difficulty: 'Moderate',
    tags: ['waterfalls', 'glaciers', 'northern lights', 'road trip', 'photography'],
    maxGroupSize: 10, minGroupSize: 2, departureFrom: 'Delhi or Mumbai',
    bestTimeToVisit: 'September to March for aurora, June to August for midnight sun',
    climate: 'Cold 0-15C, layered clothing essential',
    language: 'Icelandic, English widely spoken', currency_local: 'ISK', visaRequired: true,
    visaInfo: 'Schengen visa required. Apply well in advance. We provide full documentation support.',
    highlights: ['Golden Circle', 'Jokulsarlon glacier lagoon', 'Reynisfjara black sand beach', 'Blue Lagoon geothermal spa', 'Northern Lights hunt in season'],
    included: ['8 nights accommodation', 'Daily breakfast', 'Blue Lagoon entry', 'Glacier lagoon boat', 'Northern Lights tour in season', 'All transfers and guiding'],
    excluded: ['International flights', 'Schengen visa', 'Most meals', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Reykjavik', description: 'Transfer to the world\'s northernmost capital. Evening old-harbour stroll.', activities: ['Airport pickup', 'Harbour walk'], meals: M(false, false, false), accommodation: 'Hotel, Reykjavik' },
      { day: 2, title: 'Golden Circle', description: 'Thingvellir rift valley, Geysir hot springs, and the mighty Gullfoss waterfall.', activities: ['Thingvellir', 'Geysir', 'Gullfoss'], meals: M(true, false, false), accommodation: 'Hotel, Selfoss' },
      { day: 3, title: 'South Coast Waterfalls', description: 'Seljalandsfoss and Skogafoss waterfalls, and Reynisfjara black-sand beach.', activities: ['Seljalandsfoss', 'Skogafoss', 'Reynisfjara'], meals: M(true, false, false), accommodation: 'Hotel, Vik' },
      { day: 4, title: 'Glacier Lagoon', description: 'Jokulsarlon glacier lagoon boat and the sparkling Diamond Beach.', activities: ['Jokulsarlon boat', 'Diamond Beach'], meals: M(true, false, false), accommodation: 'Hotel, Hofn' },
      { day: 5, title: 'East Fjords', description: 'Drive the dramatic eastern fjords with fishing-village stops.', activities: ['East Fjords drive', 'Fishing villages'], meals: M(true, false, false), accommodation: 'Hotel, Egilsstadir' },
      { day: 6, title: 'Lake Myvatn', description: 'Geothermal Myvatn — mud pots, lava fields, and the nature baths.', activities: ['Myvatn nature baths', 'Dimmuborgir lava'], meals: M(true, false, false), accommodation: 'Hotel, Akureyri' },
      { day: 7, title: 'North and Waterfalls', description: 'Godafoss the waterfall of the gods, then whale-watching from Akureyri.', activities: ['Godafoss', 'Whale watching'], meals: M(true, false, false), accommodation: 'Hotel, Borgarnes' },
      { day: 8, title: 'Return via Blue Lagoon', description: 'Drive back to Reykjavik. Unwind in the milky-blue geothermal spa.', activities: ['Blue Lagoon', 'Reykjavik evening'], meals: M(true, false, false), accommodation: 'Hotel, Reykjavik' },
      { day: 9, title: 'Departure', description: 'Transfer to Keflavik airport.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Will we see the Northern Lights?', answer: 'From September to March we run aurora hunts, but the lights depend on weather and solar activity.' },
      { question: 'How cold does it get?', answer: 'Winter hovers around 0C but wind chill matters — we send a packing list.' },
    ],
    accommodationKind: 'Comfort Hotels', accommodationName: 'Handpicked hotels along the Ring Road',
    accommodationDetails: 'Warm, comfortable hotels at each overnight stop on the circuit.',
    transportTo: 'Fly to Keflavik International Airport', transportLocal: 'Private guided vehicle throughout',
    location: { lat: 64.1466, lng: -21.9426 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Masai Mara Great Migration Safari', slug: 'masai-mara-great-migration-safari',
    tagline: 'A million wildebeest. One river. Front-row seats.',
    description: 'Seven days in Kenya timed for the Great Migration — game drives across the Mara at dawn, big cats on the hunt, a Maasai village visit, and sundowners over the savanna. The greatest wildlife show on earth, seen properly.',
    destination: 'Masai Mara', country: 'Kenya', continent: 'Africa',
    coverImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
    pricePerPerson: 169999, originalPrice: 195000, currency: 'INR',
    days: 7, nights: 6, category: 'Wildlife', difficulty: 'Easy',
    tags: ['safari', 'big five', 'migration', 'photography', 'bucket list'],
    maxGroupSize: 10, minGroupSize: 2, departureFrom: 'Mumbai or Delhi',
    bestTimeToVisit: 'July to October for the migration', climate: 'Mild savanna 14-28C',
    language: 'Swahili, English', currency_local: 'KES', visaRequired: true,
    visaInfo: 'Kenya eTA required for Indian passport holders. Quick online process. We assist.',
    highlights: ['Great Migration river crossings', 'Big Five game drives', 'Maasai village visit', 'Savanna sundowner', 'Optional hot-air balloon safari'],
    included: ['6 nights safari camps', 'All meals on safari', 'Park fees', '4x4 game drives with naturalist', 'Nairobi transfers'],
    excluded: ['International flights', 'Kenya eTA', 'Balloon safari optional', 'Tips and insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Nairobi', description: 'Land in Nairobi, overnight near the national park. Trip briefing over dinner.', activities: ['Airport pickup', 'Trip briefing'], meals: M(false, false, true), accommodation: 'Eka Hotel, Nairobi' },
      { day: 2, title: 'Into the Mara', description: 'Fly or drive into the Masai Mara. Afternoon game drive as the light turns gold.', activities: ['Transfer to Mara', 'Afternoon game drive'], meals: M(true, true, true), accommodation: 'Mara Safari Camp' },
      { day: 3, title: 'Full Day on Safari', description: 'Dawn-to-dusk game drives tracking lion, cheetah, elephant and the herds.', activities: ['Sunrise game drive', 'Picnic in the bush', 'Evening drive'], meals: M(true, true, true), accommodation: 'Mara Safari Camp' },
      { day: 4, title: 'Migration River Crossings', description: 'Position along the Mara River for the migration crossings — patience, then chaos.', activities: ['River crossing watch', 'Photography session'], meals: M(true, true, true), accommodation: 'Mara Safari Camp' },
      { day: 5, title: 'Maasai Culture and Balloon Option', description: 'Optional dawn balloon safari with champagne breakfast. Afternoon Maasai village visit.', activities: ['Balloon safari optional', 'Maasai village'], meals: M(true, true, true), accommodation: 'Mara Safari Camp' },
      { day: 6, title: 'Last Game Drive, Return to Nairobi', description: 'One last dawn drive, then back to Nairobi. Farewell dinner at Carnivore.', activities: ['Dawn drive', 'Return transfer', 'Farewell dinner'], meals: M(true, false, true), accommodation: 'Eka Hotel, Nairobi' },
      { day: 7, title: 'Departure', description: 'Giraffe Centre visit if time allows, then airport.', activities: ['Giraffe Centre', 'Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Will we definitely see the migration?', answer: 'July to October the herds are in the Mara. River crossings depend on the day, but game viewing is spectacular throughout.' },
      { question: 'Is the balloon safari worth it?', answer: 'It is unforgettable — about USD 450 extra, book with us in advance.' },
    ],
    accommodationKind: 'Safari Camps', accommodationName: 'Tented safari camps inside the reserve',
    accommodationDetails: 'Comfortable en-suite tents — wild by night, luxurious by design.',
    transportTo: 'Fly to Jomo Kenyatta International Airport, Nairobi', transportLocal: '4x4 Land Cruisers with pop-up roofs',
    location: { lat: -1.4931, lng: 35.1439 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Ranthambore Tiger Trails', slug: 'ranthambore-tiger-trails',
    tagline: 'Where the jungle still keeps its king',
    description: 'Four days in Ranthambore National Park — six safari drives through dhok forest and ancient ruins in search of wild tigers, plus leopards, sloth bears and 300 bird species. India\'s best tiger odds, done right.',
    destination: 'Ranthambore, Rajasthan', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1549366021-9f761d450615?w=800', 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800'],
    pricePerPerson: 21999, originalPrice: 26000, currency: 'INR',
    days: 4, nights: 3, category: 'Wildlife', difficulty: 'Easy',
    tags: ['tigers', 'safari', 'birding', 'photography', 'weekend'],
    maxGroupSize: 12, minGroupSize: 2, departureFrom: 'Delhi or Jaipur',
    bestTimeToVisit: 'October to April; May-June for best sightings', climate: 'Dry 15-35C by season',
    language: 'Hindi', currency_local: 'INR', visaRequired: false,
    highlights: ['Six zone-permit safari drives', 'Ranthambore Fort at sunset', 'Expert naturalist on every drive', 'Padam Talao lake hides', 'Village craft visit'],
    included: ['3 nights jungle lodge', 'All meals', 'Six shared canter/gypsy safaris', 'Park permits', 'Naturalist guide'],
    excluded: ['Travel to Sawai Madhopur', 'Camera fees', 'Tips', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Sawai Madhopur', description: 'Train in from Delhi or Jaipur. Evening at Ranthambore Fort overlooking the park.', activities: ['Arrival', 'Ranthambore Fort'], meals: M(false, false, true), accommodation: 'Jungle lodge, Ranthambore' },
      { day: 2, title: 'Safari Day One', description: 'Dawn and afternoon drives in the core zones. Tigers, if the jungle wills it.', activities: ['Morning safari', 'Afternoon safari'], meals: M(true, true, true), accommodation: 'Jungle lodge, Ranthambore' },
      { day: 3, title: 'Safari Day Two', description: 'Two more drives across different zones — leopards, sloth bears, crocodiles at the lakes.', activities: ['Morning safari', 'Afternoon safari', 'Wildlife talk'], meals: M(true, true, true), accommodation: 'Jungle lodge, Ranthambore' },
      { day: 4, title: 'Final Drive and Departure', description: 'One last dawn drive, brunch, and onward travel.', activities: ['Dawn safari', 'Departure'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'What are the odds of seeing a tiger?', answer: 'With six drives across zones, most guests sight tigers at least once — but it is wild, never guaranteed.' },
      { question: 'Gypsy or canter?', answer: 'We book 6-seater gypsies where permits allow — quieter and better for photography.' },
    ],
    accommodationKind: 'Jungle Lodge', accommodationName: 'Boutique lodge near the park gate',
    accommodationDetails: 'Cottages with verandas, a pool, and resident birdlife.',
    transportTo: 'Train to Sawai Madhopur from Delhi or Jaipur', transportLocal: 'Open 4x4 gypsies inside the park',
    location: { lat: 26.0173, lng: 76.5026 },
    isFeatured: false, rating: 0, reviewCount: 0,
  },
  {
    title: 'Andaman Island Escape', slug: 'andaman-island-escape',
    tagline: 'India\'s clearest water, without the passport',
    description: 'Six days across Port Blair, Havelock and Neil — Radhanagar Beach sunsets, scuba over living coral, bioluminescent kayaking, and long island afternoons where the only plan is no plan.',
    destination: 'Port Blair, Havelock and Neil', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800', 'https://images.unsplash.com/photo-1505881502353-a1986add3762?w=800'],
    pricePerPerson: 36999, originalPrice: 44000, currency: 'INR',
    days: 6, nights: 5, category: 'Beach', difficulty: 'Easy',
    tags: ['beaches', 'scuba', 'islands', 'snorkelling', 'no visa'],
    maxGroupSize: 14, minGroupSize: 2, departureFrom: 'Chennai, Kolkata or Delhi',
    bestTimeToVisit: 'November to May', climate: 'Tropical 24-31C',
    language: 'Hindi, Bengali, Tamil', currency_local: 'INR', visaRequired: false,
    highlights: ['Radhanagar Beach — Asia\'s finest', 'Discover Scuba dive', 'Bioluminescence night kayak', 'Cellular Jail light and sound show', 'Neil Island cycling'],
    included: ['5 nights hotels and resorts', 'Daily breakfast', 'All ferry transfers', 'Scuba intro dive', 'Cellular Jail show', 'Airport transfers'],
    excluded: ['Flights to Port Blair', 'Lunches and dinners', 'Optional water sports', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Port Blair', description: 'Land at Veer Savarkar airport. Evening Cellular Jail light and sound show.', activities: ['Airport pickup', 'Cellular Jail show'], meals: M(false, false, false), accommodation: 'Hotel, Port Blair' },
      { day: 2, title: 'Ferry to Havelock', description: 'Morning ferry to Swaraj Dweep. Sunset at Radhanagar Beach.', activities: ['Ferry to Havelock', 'Radhanagar sunset'], meals: M(true, false, false), accommodation: 'Beach resort, Havelock' },
      { day: 3, title: 'Scuba and Elephant Beach', description: 'Discover Scuba dive over the reef, then snorkelling at Elephant Beach.', activities: ['Scuba dive', 'Elephant Beach snorkel'], meals: M(true, false, false), accommodation: 'Beach resort, Havelock' },
      { day: 4, title: 'Neil Island', description: 'Ferry to Neil. Cycle between beaches, natural rock bridge at low tide.', activities: ['Ferry to Neil', 'Island cycling', 'Natural bridge'], meals: M(true, false, false), accommodation: 'Resort, Neil Island' },
      { day: 5, title: 'Back to Port Blair', description: 'Slow morning, afternoon ferry back. Optional bioluminescence kayak after dark.', activities: ['Free morning', 'Night kayak optional'], meals: M(true, false, false), accommodation: 'Hotel, Port Blair' },
      { day: 6, title: 'Departure', description: 'Transfer to the airport with sand still in your shoes.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Do Indians need any permit?', answer: 'No permit needed for these islands for Indian nationals — just a photo ID.' },
      { question: 'Can non-swimmers scuba?', answer: 'Yes — the intro dive needs no swimming skills; instructors handle everything.' },
    ],
    accommodationKind: 'Beach Resorts', accommodationName: 'Handpicked resorts on Havelock and Neil',
    accommodationDetails: 'Beachfront cottages a barefoot walk from the water.',
    transportTo: 'Fly to Port Blair (Veer Savarkar International)', transportLocal: 'Private cabs plus government and private ferries',
    location: { lat: 11.9762, lng: 92.9503 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Meghalaya Caves and Waterfalls', slug: 'meghalaya-caves-and-waterfalls',
    tagline: 'The abode of clouds, roots and rain',
    description: 'Six days in the wettest place on earth — trekking to double-decker living root bridges, swimming beneath Krang Suri falls, caving in Mawsmai, and boating the glass-clear Umngot river at Dawki.',
    destination: 'Shillong, Cherrapunji and Dawki', country: 'India', continent: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800', 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800'],
    pricePerPerson: 26999, originalPrice: 32000, currency: 'INR',
    days: 6, nights: 5, category: 'Adventure', difficulty: 'Moderate',
    tags: ['waterfalls', 'trekking', 'caves', 'root bridges', 'offbeat'],
    maxGroupSize: 12, minGroupSize: 4, departureFrom: 'Guwahati',
    bestTimeToVisit: 'October to April; monsoon for full waterfalls', climate: 'Cool and wet 12-24C',
    language: 'Khasi, English', currency_local: 'INR', visaRequired: false,
    highlights: ['Double-decker living root bridge trek', 'Umngot crystal river at Dawki', 'Krang Suri waterfall swim', 'Mawsmai and Arwah caves', 'Cleanest village in Asia, Mawlynnong'],
    included: ['5 nights hotels and homestays', 'Breakfast and dinner', 'All transfers from Guwahati', 'Trek guide', 'Boating at Dawki'],
    excluded: ['Flights to Guwahati', 'Lunch', 'Camera fees', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Guwahati to Shillong', description: 'Drive up past Umiam Lake into the Scotland of the East.', activities: ['Umiam Lake stop', 'Shillong arrival'], meals: M(false, false, true), accommodation: 'Hotel, Shillong' },
      { day: 2, title: 'Shillong to Cherrapunji', description: 'Waterfall circuit — Elephant Falls, Wei Sawdong\'s three tiers, canyon viewpoints.', activities: ['Elephant Falls', 'Wei Sawdong', 'Canyon viewpoints'], meals: M(true, false, true), accommodation: 'Resort, Cherrapunji' },
      { day: 3, title: 'Double-Decker Root Bridge Trek', description: '3,500 steps down to Nongriat\'s living root bridge and natural pools. Earn it, swim it.', activities: ['Nongriat trek', 'Natural pool swim'], meals: M(true, false, true), accommodation: 'Resort, Cherrapunji' },
      { day: 4, title: 'Caves and Mawlynnong', description: 'Mawsmai limestone caves, then Asia\'s cleanest village and its sky-walk views of Bangladesh.', activities: ['Mawsmai caves', 'Mawlynnong village', 'Sky walk'], meals: M(true, false, true), accommodation: 'Homestay, Mawlynnong area' },
      { day: 5, title: 'Dawki and Krang Suri', description: 'Boat the transparent Umngot river, then a turquoise swim beneath Krang Suri falls.', activities: ['Dawki boating', 'Krang Suri swim'], meals: M(true, false, true), accommodation: 'Hotel, Shillong' },
      { day: 6, title: 'Return to Guwahati', description: 'Cafe morning in Shillong, then down to Guwahati for onward travel.', activities: ['Shillong cafes', 'Departure'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'How hard is the root bridge trek?', answer: 'About 3,500 steps each way — steep but staired. A basic fitness level and good shoes are enough.' },
      { question: 'Is monsoon a good time?', answer: 'Waterfalls are at full glory but treks get slippery. Oct-Apr is the comfortable window.' },
    ],
    accommodationKind: 'Hotels and Homestays', accommodationName: 'Shillong hotels, Cherrapunji resort, Khasi homestay',
    accommodationDetails: 'Warm local stays with hill views and better breakfasts than you expect.',
    transportTo: 'Fly to Guwahati (LGBI Airport)', transportLocal: 'Private SUV throughout',
    location: { lat: 25.2841, lng: 91.7217 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
  {
    title: 'Mauritius Honeymoon Bliss', slug: 'mauritius-honeymoon-bliss',
    tagline: 'Turquoise mornings, golden evenings, just you two',
    description: 'Six days of island romance — a beachfront resort on the west coast, catamaran cruise to Île aux Cerfs, the seven-coloured earths of Chamarel, underwater walks, and one candlelit dinner on the sand.',
    destination: 'West Coast, Mauritius', country: 'Mauritius', continent: 'Africa',
    coverImage: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=1200&q=80',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800', 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800'],
    pricePerPerson: 89999, originalPrice: 105000, currency: 'INR',
    days: 6, nights: 5, category: 'Honeymoon', difficulty: 'Easy',
    tags: ['honeymoon', 'beach', 'catamaran', 'couples', 'no visa'],
    maxGroupSize: 8, minGroupSize: 2, departureFrom: 'Mumbai, Delhi or Bengaluru',
    bestTimeToVisit: 'May to December', climate: 'Tropical 22-30C',
    language: 'English, French, Creole', currency_local: 'MUR', visaRequired: false,
    visaInfo: 'Visa on arrival free for Indian passport holders.',
    highlights: ['Catamaran cruise to Île aux Cerfs', 'Chamarel seven-coloured earths', 'Candlelit beach dinner', 'Underwater sea walk', 'Sunset at Flic en Flac'],
    included: ['5 nights beachfront resort', 'Daily breakfast and dinner', 'Catamaran day cruise with lunch', 'South island tour', 'Candlelit dinner', 'Airport transfers'],
    excluded: ['International flights', 'Lunches on free days', 'Spa treatments', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrive in Paradise', description: 'Land in Mauritius, transfer to your beachfront resort. Sunset toast on the sand.', activities: ['Airport pickup', 'Resort check-in', 'Sunset toast'], meals: M(false, false, true), accommodation: 'Beachfront resort, west coast' },
      { day: 2, title: 'Catamaran to Île aux Cerfs', description: 'Full-day sail — snorkelling stops, grilled lunch on board, an island that looks photoshopped.', activities: ['Catamaran cruise', 'Snorkelling', 'Île aux Cerfs'], meals: M(true, true, true), accommodation: 'Beachfront resort' },
      { day: 3, title: 'South Island Wonders', description: 'Chamarel coloured earths, sacred Grand Bassin lake, Black River Gorges viewpoints.', activities: ['Chamarel', 'Grand Bassin', 'Black River Gorges'], meals: M(true, false, true), accommodation: 'Beachfront resort' },
      { day: 4, title: 'Lagoon Day', description: 'Optional underwater sea walk or couples spa. Afternoon exactly as slow as you like.', activities: ['Sea walk optional', 'Free afternoon'], meals: M(true, false, true), accommodation: 'Beachfront resort' },
      { day: 5, title: 'Port Louis and Candlelight', description: 'Morning at Port Louis market and Caudan waterfront. Private candlelit dinner on the beach.', activities: ['Port Louis', 'Candlelit beach dinner'], meals: M(true, false, true), accommodation: 'Beachfront resort' },
      { day: 6, title: 'Departure', description: 'One last swim, then home with the tan and the stories.', activities: ['Airport transfer'], meals: M(true, false, false), accommodation: '' },
    ],
    faqs: [
      { question: 'Do Indians need a visa?', answer: 'No — free visa on arrival with a return ticket and hotel booking.' },
      { question: 'Best months for honeymooners?', answer: 'May to December is dry and pleasant; avoid cyclone-prone Jan-Feb.' },
    ],
    accommodationKind: 'Beachfront Resort', accommodationName: '4-star beachfront resort with lagoon access',
    accommodationDetails: 'Sea-view rooms, pool bar, and a beach that empties by dusk.',
    transportTo: 'Fly to SSR International Airport, Mauritius', transportLocal: 'Private car plus catamaran',
    location: { lat: -20.2765, lng: 57.3728 },
    isFeatured: true, rating: 0, reviewCount: 0,
  },
];
